-- CreateTable
CREATE TABLE "search_index_entry" (
    "subject_type" "subject_type" NOT NULL,
    "subject_id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "facets_json" JSONB NOT NULL DEFAULT '{}',
    "acl_tokens" TEXT[],
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "search_index_entry_pkey" PRIMARY KEY ("subject_type","subject_id")
);

-- CreateIndex
CREATE INDEX "search_index_entry_department_id_idx" ON "search_index_entry"("department_id");

-- CreateIndex
CREATE INDEX "search_index_entry_acl_tokens_idx" ON "search_index_entry" USING GIN ("acl_tokens");

-- AddForeignKey
ALTER TABLE "search_index_entry" ADD CONSTRAINT "search_index_entry_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Hand-written (design part 04 §22.4). The column Prisma cannot express: the text of a row,
-- weighted so a hit in the title outranks a hit in the body, maintained by PostgreSQL itself so
-- no writer can forget it. `simple` rather than `english`: the corpus is Amharic and English
-- names, codes and titles, where stemming does more harm than good.
ALTER TABLE "search_index_entry"
  ADD COLUMN "search" tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce("title", '')), 'A') ||
    setweight(to_tsvector('simple', coalesce("body_text", '')), 'B')
  ) STORED;

CREATE INDEX search_index_entry_search_idx ON "search_index_entry" USING GIN ("search");

-- Prefix suggestions ("cs2" -> CS201) come from trigrams rather than from the tsvector. The
-- extension goes into `public` and its operator class is named with that schema: a test run
-- migrates into a schema of its own, and an extension installed into one of those would be
-- invisible (or dropped) the next time.
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE INDEX IF NOT EXISTS course_title_trgm ON "course" USING GIN ("title" public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS document_title_trgm ON "document" USING GIN ("title" public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS search_index_entry_title_trgm
  ON "search_index_entry" USING GIN ("title" public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS document_version_text_gin
  ON "document_version" USING GIN (to_tsvector('simple', coalesce("extracted_text", '')));

-- generated by gen-rls.ts; manifest-hash=c023d6d262c3d40f9878822ec4da5031df070e3db76926065563d8e11b94cd30
-- tenant: SearchIndexEntry
ALTER TABLE "search_index_entry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "search_index_entry" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "search_index_entry"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');
