-- CreateTable
CREATE TABLE "availability_policy" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "owner_person_id" TEXT NOT NULL,
    "purpose" "policy_purpose" NOT NULL,
    "weekly_windows_json" JSONB NOT NULL,
    "slot_minutes" INTEGER,
    "max_per_period" INTEGER,
    "break_windows_json" JSONB NOT NULL DEFAULT '[]',
    "blackout_periods_json" JSONB NOT NULL DEFAULT '[]',
    "valid_from" DATE NOT NULL,
    "valid_to" DATE,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "availability_policy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "availability_block" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "owner_type" "owner_type" NOT NULL,
    "owner_id" TEXT NOT NULL,
    "start_at" TIMESTAMP(3) NOT NULL,
    "end_at" TIMESTAMP(3) NOT NULL,
    "weekday" INTEGER,
    "week_pattern" "week_pattern",
    "recurring_from" TIMESTAMP(3),
    "recurring_until" TIMESTAMP(3),
    "kind" "block_kind" NOT NULL,
    "severity" "severity" NOT NULL,
    "source_type" "subject_type",
    "source_id" TEXT,
    "term_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "availability_block_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "availability_policy_owner_person_id_purpose_idx" ON "availability_policy"("owner_person_id", "purpose");

-- CreateIndex
CREATE INDEX "availability_policy_department_id_idx" ON "availability_policy"("department_id");

-- CreateIndex
CREATE INDEX "availability_block_owner_type_owner_id_start_at_idx" ON "availability_block"("owner_type", "owner_id", "start_at");

-- CreateIndex
CREATE INDEX "availability_block_source_type_source_id_idx" ON "availability_block"("source_type", "source_id");

-- CreateIndex
CREATE INDEX "availability_block_department_id_idx" ON "availability_block"("department_id");

-- AddForeignKey
ALTER TABLE "availability_policy" ADD CONSTRAINT "availability_policy_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_policy" ADD CONSTRAINT "availability_policy_owner_person_id_fkey" FOREIGN KEY ("owner_person_id") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_block" ADD CONSTRAINT "availability_block_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_block" ADD CONSTRAINT "availability_block_term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "term"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- generated by gen-rls.ts; manifest-hash=cc80c004c2e0a2f5efd4093b69a92442a3f7d4d99dab056ad175ff0fbb7fe38a
-- tenant: AvailabilityBlock
ALTER TABLE "availability_block" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "availability_block" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "availability_block"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');

-- tenant: AvailabilityPolicy
ALTER TABLE "availability_policy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "availability_policy" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "availability_policy"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');
