import type { Readable } from "node:stream";

// The storage seam (design part 06, P6): the document service is the only caller. Keys are
// opaque and generated by the provider — never derived from user input — so a provider can
// be swapped (local disk today, S3-compatible later) without touching the rest.

export interface PutMeta {
  mimeType: string;
}

export interface StoredObject {
  key: string;
  sizeBytes: number;
  /** Lower-case hex sha256 of the bytes. */
  checksum: string;
}

export interface StorageProvider {
  put(source: Readable | Buffer, meta: PutMeta): Promise<StoredObject>;
  get(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export class StorageKeyError extends Error {
  constructor(key: string) {
    super(`Malformed storage key "${key}"`);
    this.name = "StorageKeyError";
  }
}

export class StorageObjectNotFoundError extends Error {
  constructor(key: string) {
    super(`Stored object "${key}" not found`);
    this.name = "StorageObjectNotFoundError";
  }
}

/** yyyy/mm/<32 hex>: the only shape a key may have, whatever the provider. */
export const KEY_PATTERN = /^\d{4}\/(0[1-9]|1[0-2])\/[a-f0-9]{32}$/;

export function assertKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new StorageKeyError(key);
}
