-- CreateTable
CREATE TABLE "dashboard_projection" (
    "projection_key" TEXT NOT NULL,
    "row_key" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "dimensions_json" JSONB NOT NULL DEFAULT '{}',
    "values_json" JSONB NOT NULL DEFAULT '{}',
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "dashboard_projection_pkey" PRIMARY KEY ("projection_key","row_key")
);

-- CreateIndex
CREATE INDEX "dashboard_projection_department_id_projection_key_idx" ON "dashboard_projection"("department_id", "projection_key");

-- AddForeignKey
ALTER TABLE "dashboard_projection" ADD CONSTRAINT "dashboard_projection_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- generated by gen-rls.ts; manifest-hash=5a6c7681dd0d477c72d82fc4abc8ab908f08a43dc7a47fb3eb49059f8d4168f8
-- tenant: DashboardProjection
ALTER TABLE "dashboard_projection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dashboard_projection" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "dashboard_projection"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');
