import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { loadDmmf, loadSchemaFiles, type SchemaFile } from "../../../prisma/scripts/dmmf";
import {
  buildManifest,
  check,
  classify,
  policySql,
  uncoveredSql,
  readManifest,
} from "../../../prisma/scripts/gen-rls";

function fixture(name: string): SchemaFile {
  const path = resolve("tests/fixtures/schemas", name);
  return [path, readFileSync(path, "utf8")];
}

describe("gen-rls classification", () => {
  it("classifies required departmentId as tenant, optional as shared, none as global", async () => {
    const tables = classify(await loadDmmf([fixture("classification.prisma")]));
    const byTable = Object.fromEntries(tables.map((t) => [t.table, t]));
    expect(byTable["strict_thing"]?.kind).toBe("tenant");
    expect(byTable["shared_thing"]?.kind).toBe("shared");
    expect(byTable["global_thing"]?.kind).toBe("global");
    expect(byTable["department"]?.kind).toBe("global");
    expect(byTable["strict_thing"]?.column).toBe("department_id");
  });

  it("emits strict and nullable policies with snake_case identifiers from the DMMF", async () => {
    const tables = classify(await loadDmmf([fixture("classification.prisma")]));
    const strict = policySql(tables.find((t) => t.table === "strict_thing")!);
    expect(strict).toContain('ALTER TABLE "strict_thing" FORCE ROW LEVEL SECURITY;');
    expect(strict).toContain(`CREATE POLICY tenant_isolation ON "strict_thing"`);
    expect(strict).toContain(
      `"department_id" = current_setting('app.current_department_id', true)`,
    );
    expect(strict).not.toContain("IS NULL");
    expect(strict).not.toContain("departmentId");

    const shared = policySql(tables.find((t) => t.table === "shared_thing")!);
    expect(shared).toContain(`USING ("department_id" IS NULL OR`);
    expect(shared).toContain(
      `WITH CHECK (("department_id" IS NULL AND current_setting('app.tenant_bypass', true) = 'on') OR`,
    );

    expect(policySql(tables.find((t) => t.table === "global_thing")!)).toBe("");
  });

  it("produces deterministic, sorted SQL and skips covered tables", async () => {
    const tables = classify(await loadDmmf([fixture("classification.prisma")]));
    const all = uncoveredSql(tables, new Set());
    expect(all.indexOf('"shared_thing"')).toBeLessThan(all.indexOf('"strict_thing"'));
    expect(all.startsWith("-- generated by gen-rls.ts; manifest-hash=")).toBe(true);
    expect(uncoveredSql(tables, new Set(["shared_thing", "strict_thing"]))).toBe("");
    expect(uncoveredSql(tables, new Set())).toBe(all);
  });

  it("check fails for a stale manifest, an uncovered tenant table and a missing Department relation", async () => {
    const tables = classify(
      await loadDmmf([fixture("classification.prisma"), fixture("unrelated.prisma")]),
    );
    const stale = check(tables, { tenant: [], shared: [], global: [], hash: "stale" }, new Set());
    expect(stale.ok).toBe(false);
    expect(stale.problems.join("\n")).toMatch(/stale/);
    expect(stale.problems.join("\n")).toMatch(/orphan.*not classified/);
    expect(stale.problems.join("\n")).toMatch(/strict_thing has no tenant_isolation policy/);
    expect(stale.problems.join("\n")).toMatch(/Orphan has departmentId without a relation/);

    const fresh = buildManifest(tables);
    const covered = new Set(["strict_thing", "shared_thing", "orphan"]);
    const result = check(tables, fresh, covered);
    expect(result.problems).toEqual([
      "model Orphan has departmentId without a relation to Department",
    ]);
  });

  it("the committed manifest matches the real schema", async () => {
    const tables = classify(await loadDmmf(loadSchemaFiles()));
    const manifest = readManifest();
    expect(manifest).not.toBeNull();
    expect(manifest!.hash).toBe(buildManifest(tables).hash);
    expect(manifest!.global).toContain("system_setting");
  });
});
