-- CreateTable
CREATE TABLE "committee" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "purpose" TEXT,
    "type" TEXT,
    "start_date" DATE,
    "end_date" DATE,
    "chair_person_id" TEXT,
    "group_id" TEXT NOT NULL,
    "responsibilities_text" TEXT,
    "feature_record_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "committee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "committee_report" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "committee_id" TEXT NOT NULL,
    "period_from" DATE NOT NULL,
    "period_to" DATE NOT NULL,
    "author_person_id" TEXT NOT NULL,
    "submission_id" TEXT,
    "feature_record_id" TEXT NOT NULL,
    "submitted_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "committee_report_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "committee_group_id_key" ON "committee"("group_id");

-- CreateIndex
CREATE UNIQUE INDEX "committee_feature_record_id_key" ON "committee"("feature_record_id");

-- CreateIndex
CREATE INDEX "committee_department_id_idx" ON "committee"("department_id");

-- CreateIndex
CREATE UNIQUE INDEX "committee_report_submission_id_key" ON "committee_report"("submission_id");

-- CreateIndex
CREATE UNIQUE INDEX "committee_report_feature_record_id_key" ON "committee_report"("feature_record_id");

-- CreateIndex
CREATE INDEX "committee_report_committee_id_idx" ON "committee_report"("committee_id");

-- CreateIndex
CREATE INDEX "committee_report_department_id_idx" ON "committee_report"("department_id");

-- AddForeignKey
ALTER TABLE "committee" ADD CONSTRAINT "committee_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "committee" ADD CONSTRAINT "committee_chair_person_id_fkey" FOREIGN KEY ("chair_person_id") REFERENCES "person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "committee" ADD CONSTRAINT "committee_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "committee_report" ADD CONSTRAINT "committee_report_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "committee_report" ADD CONSTRAINT "committee_report_committee_id_fkey" FOREIGN KEY ("committee_id") REFERENCES "committee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "committee_report" ADD CONSTRAINT "committee_report_author_person_id_fkey" FOREIGN KEY ("author_person_id") REFERENCES "person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- generated by gen-rls.ts; manifest-hash=92046de024e155adc6475b6b935d0f26e85f9e2de392e5f55120f1e116b047e1
-- tenant: Committee
ALTER TABLE "committee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "committee" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "committee"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');

-- tenant: CommitteeReport
ALTER TABLE "committee_report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "committee_report" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "committee_report"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');
