-- CreateTable
CREATE TABLE "report_definition" (
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "data_source_key" TEXT NOT NULL,
    "template_key" TEXT NOT NULL,
    "parameters_schema_json" JSONB NOT NULL,
    "supported_formats" "report_format"[],
    "required_permission" TEXT NOT NULL,
    "schedule_spec_json" JSONB,
    "is_system" BOOLEAN NOT NULL DEFAULT true,
    "feature_key" TEXT,

    CONSTRAINT "report_definition_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "generated_report" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "report_key" TEXT NOT NULL,
    "params_json" JSONB NOT NULL,
    "format" "report_format" NOT NULL,
    "document_id" TEXT,
    "requested_by" TEXT NOT NULL,
    "status" "report_status" NOT NULL DEFAULT 'queued',
    "error" TEXT,
    "generated_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "generated_report_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "export_format_spec" (
    "id" TEXT NOT NULL,
    "department_id" TEXT,
    "name" TEXT NOT NULL,
    "target_system" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "file_format" "file_format" NOT NULL,
    "sheet_name" TEXT,
    "header_row_index" INTEGER NOT NULL DEFAULT 1,
    "columns_json" JSONB NOT NULL,
    "row_source" "export_row_source" NOT NULL,
    "golden_sample_document_id" TEXT,
    "status" "version_status" NOT NULL DEFAULT 'draft',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "export_format_spec_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "generated_report_department_id_report_key_created_at_idx" ON "generated_report"("department_id", "report_key", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "export_format_spec_department_id_name_version_key" ON "export_format_spec"("department_id", "name", "version");

-- AddForeignKey
ALTER TABLE "generated_report" ADD CONSTRAINT "generated_report_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "generated_report" ADD CONSTRAINT "generated_report_report_key_fkey" FOREIGN KEY ("report_key") REFERENCES "report_definition"("key") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "export_format_spec" ADD CONSTRAINT "export_format_spec_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- generated by gen-rls.ts; manifest-hash=af872fe917add7ed1bc24bc8d40b5ece53302164894a6d765d78a83c74451cc5
-- shared: ExportFormatSpec
ALTER TABLE "export_format_spec" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "export_format_spec" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "export_format_spec"
  USING ("department_id" IS NULL OR "department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK (("department_id" IS NULL AND current_setting('app.tenant_bypass', true) = 'on') OR "department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');

-- tenant: GeneratedReport
ALTER TABLE "generated_report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "generated_report" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "generated_report"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');
