-- CreateTable
CREATE TABLE "import_batch" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "kind" "import_kind" NOT NULL,
    "context_type" "subject_type",
    "context_id" TEXT,
    "source_document_id" TEXT,
    "mapping_profile_id" TEXT,
    "mode" "import_mode" NOT NULL DEFAULT 'file',
    "feature_record_id" TEXT NOT NULL,
    "summary_json" JSONB NOT NULL DEFAULT '{}',
    "uploaded_by" TEXT NOT NULL,
    "committed_at" TIMESTAMP(3),
    "replaces_batch_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "import_batch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "import_row" (
    "id" TEXT NOT NULL,
    "department_id" TEXT NOT NULL,
    "batch_id" TEXT NOT NULL,
    "row_no" INTEGER NOT NULL,
    "raw_json" JSONB NOT NULL,
    "normalized_json" JSONB,
    "errors_json" JSONB NOT NULL DEFAULT '[]',
    "warnings_json" JSONB NOT NULL DEFAULT '[]',
    "disposition" "disposition" NOT NULL DEFAULT 'ok',

    CONSTRAINT "import_row_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "column_mapping_profile" (
    "id" TEXT NOT NULL,
    "department_id" TEXT,
    "kind" "import_kind" NOT NULL,
    "name" TEXT NOT NULL,
    "sheet_name" TEXT,
    "header_row_index" INTEGER NOT NULL DEFAULT 1,
    "mappings_json" JSONB NOT NULL,
    "header_aliases_json" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "column_mapping_profile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "import_batch_feature_record_id_key" ON "import_batch"("feature_record_id");

-- CreateIndex
CREATE INDEX "import_batch_context_type_context_id_kind_idx" ON "import_batch"("context_type", "context_id", "kind");

-- CreateIndex
CREATE INDEX "import_batch_department_id_kind_idx" ON "import_batch"("department_id", "kind");

-- CreateIndex
CREATE INDEX "import_row_batch_id_disposition_idx" ON "import_row"("batch_id", "disposition");

-- CreateIndex
CREATE INDEX "import_row_department_id_idx" ON "import_row"("department_id");

-- CreateIndex
CREATE UNIQUE INDEX "import_row_batch_id_row_no_key" ON "import_row"("batch_id", "row_no");

-- CreateIndex
CREATE UNIQUE INDEX "column_mapping_profile_department_id_kind_name_key" ON "column_mapping_profile"("department_id", "kind", "name");

-- AddForeignKey
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_mapping_profile_id_fkey" FOREIGN KEY ("mapping_profile_id") REFERENCES "column_mapping_profile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_replaces_batch_id_fkey" FOREIGN KEY ("replaces_batch_id") REFERENCES "import_batch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_row" ADD CONSTRAINT "import_row_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_row" ADD CONSTRAINT "import_row_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "import_batch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "column_mapping_profile" ADD CONSTRAINT "column_mapping_profile_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- generated by gen-rls.ts; manifest-hash=ad618c1a7883327f3b4b2d463acb3cf7987d32231901b36a30669d302327f510
-- shared: ColumnMappingProfile
ALTER TABLE "column_mapping_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "column_mapping_profile" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "column_mapping_profile"
  USING ("department_id" IS NULL OR "department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK (("department_id" IS NULL AND current_setting('app.tenant_bypass', true) = 'on') OR "department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');

-- tenant: ImportBatch
ALTER TABLE "import_batch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_batch" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "import_batch"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');

-- tenant: ImportRow
ALTER TABLE "import_row" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_row" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "import_row"
  USING ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on')
  WITH CHECK ("department_id" = current_setting('app.current_department_id', true) OR current_setting('app.tenant_bypass', true) = 'on');
